name: Notify API on PR Open

on:
  pull_request:
    types:
      - opened

jobs:
  notify_api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get PR Information
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          repo_name="${{ github.repository }}"
          repo_owner=$(echo $repo_name | cut -d'/' -f1)
          repo_name=$(echo $repo_name | cut -d'/' -f2)
          files=$(git diff --name-only $pr_number)

          echo "PR Number: $pr_number"
          echo "Repository Owner: $repo_owner"
          echo "Repository Name: $repo_name"
          echo "Changed Files: $files"

          # Call your API with the PR information and GitHub token
          api_url="http://localhost:4043/startReview"
          github_token="${{ secrets.GITHUB_TOKEN }}"
          curl -X POST -H "Content-Type: application/json" -d '{
              "prId": "'$pr_number'",
              "files": "'$files'",
              "githubToken": "'$github_token'"
          }' $api_url

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
