name: Notify API on PR Open

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify_api:
    runs-on: ubuntu-latest

    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REPO_FULL_NAME: ${{ github.repository }}
      PR_BRANCH: ${{ github.event.pull_request.head.ref }}
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.repository_name }}
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get PR Information
        run: |
          echo "PR Number: $PR_NUMBER"
          echo "Repository Owner: $REPO_OWNER"
          echo "Repository Name: $REPO_NAME"
          echo "Base branch Name: $BASE_BRANCH"

      - name: Get the files
        run: |
          files_response=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${REPO_FULL_NAME}/pulls/${PR_NUMBER}/files")

          # Extract filenames from the JSON response using jq
          files=$(echo "$files_response" | jq -r '.[].filename')

          # Check if there's only one file
          if [[ $(echo "$files" | wc -l) -eq 1 ]]; then
            changed_files="$files"
          else
            # Convert the list of files to a comma-separated string
            changed_files=$(echo "$files" | tr '\n' ',' | sed 's/,$//')
          fi

          echo "Files: $changed_files"

      - name: Call the WrapperService
        run: |
          echo "Base branch Name: $BASE_BRANCH"
          if [ "$BASE_BRANCH" == "main" ] || [ "$BASE_BRANCH" == "master" ]; then
            api_url="https://devcompanion.cc-tooling.devtools.capillarytech.com/startReview"
            github_token="${{ secrets.MY_GITHUB_TOKEN }}"
            curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.MY_WRAPPERSERVICE_AUTH_TOKEN }}" -d "{
                \"prId\": \"${PR_NUMBER}\",
                \"files\": \"${changed_files}\",
                \"repoName\": \"${REPO_NAME}\",
                \"repoOwner\": \"${REPO_OWNER}\",
                \"githubToken\": \"${github_token}\"
            }" "$api_url"
          else
            echo "PR is not raised to the master branch. Skipping the review."
          fi