name: Notify API on PR Open

on:
  pull_request:
    types:
      - opened

jobs:
  notify_api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get PR Information
        run: |
          pr_number="${{ github.event.pull_request.number }}"
          repo_full_name="${{ github.repository }}"
          pr_branch="${{ github.event.pull_request.head.ref }}"
          repo_owner=$(echo $repo_full_name | cut -d'/' -f1)
          repo_name=$(echo $repo_full_name | cut -d'/' -f2)

          echo "PR Number: $pr_number"
          echo "Repository Owner: $repo_owner"
          echo "Repository Name: $repo_name"

          files_response=$(curl -s -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files")
          sleep 5
          
          # Extract filenames from the JSON response using jq
          files=$(echo "$files_response" | jq -r '.[].filename')

          # Check if there's only one file
          if [[ $(echo "$files" | wc -l) -eq 1 ]]; then
            changed_files="$files"
          else
            # Convert the list of files to a comma-separated string
            changed_files=$(echo "$files" | tr '\n' ',' | sed 's/,$//')
          fi
          
          echo "Files: $changed_files"
          
          sleep 5
          changed_files="${{ steps.modified_files.outputs.modified_files }}"
          echo "Files Name: $changed_files"

          # Call your API with the PR information and the ngrok public URL
          api_url="https://abe2-103-215-237-139.ngrok-free.app/startReview"
          github_token="${{ secrets.MY_GITHUB_TOKEN }}"
          curl -X POST -H "Content-Type: application/json" -d "{
              \"prId\": \"${pr_number}\",
              \"files\": \"${changed_files}\",
              \"githubToken\": \"${github_token}\"
          }" "$api_url"
